sudo: enabled
language: python

matrix:
  include:
    - os: linux
      dist: xenial
      python: 2.7
      env: TOXENV=ubuntu_py27
    - os: linux
      dist: xenial
      python: 3.6
      env: TOXENV=ubuntu_py36
    - os: linux
      dist: xenial
      python: 3.7
      env: TOXENV=ubuntu_py37
    - os: linux
      dist: xenial
      language: generic
      env:
        - TOXENV=conda_ubuntu_py2
        - CONDA_PYTHON_VERSION=2.7
        - CONDA_HOME='/home/travis'
    - os: linux
      dist: xenial
      language: generic
      env:
        - TOXENV=conda_ubuntu_py3
        - CONDA_PYTHON_VERSION=3.6
        - CONDA_HOME='/home/travis'
    - os: osx
      osx_image: xcode8.3
      language: generic
      env: TOXENV=osx_py2
    - os: osx
      osx_image: xcode8.3
      language: generic
      env: TOXENV=osx_py3
    - os: osx
      osx_image: xcode9.4
      language: generic
      env:
        - TOXENV=osx_py3_high_sierra
        - TCL_BINARY=no
    - os: osx
      osx_image: xcode9.4
      language: generic
      env:
        - TOXENV=osx_py3_high_sierra_binary
        - TCL_BINARY=yes
    - os: osx
      osx_image: xcode8.3
      language: generic
      env:
        - TOXENV=conda_osx_py2
        - CONDA_PYTHON_VERSION=2.7
        - CONDA_HOME='/Users/travis'
    - os: osx
      osx_image: xcode8.3
      language: generic
      env:
        - TOXENV=conda_osx_py3
        - CONDA_PYTHON_VERSION=3.6
        - CONDA_HOME='/Users/travis'

before_install:
  - ./.travis/before_install.sh

install:
  - ./.travis/install.sh

before_script:
  - cd $TRAVIS_BUILD_DIR
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      cp conf/ciconf_linux.py conf/userconf.py;

      case "${TOXENV}$" in
        conda*)
          sed -i "26s/.*/user_tcl_shell_cmd = 'tclsh8.4'/" conf/userconf.py;
          source $CONDA_HOME/miniconda/bin/activate;
          conda activate test-environment;
          ;;
      esac
    fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      case "${TOXENV}$" in
        conda*)
          source $CONDA_HOME/miniconda/bin/activate;
          conda activate test-environment;
          ;;
      esac

      git lfs pull;
      cp conf/ciconf_osx.py conf/userconf.py;

      case "${TRAVIS_OSX_IMAGE}" in
        xcode9*)
          sed -e "18s~.*~user_snack_lib_path = '/Users/travis/lib/snack2.2'~" -i '' conf/userconf.py;
          sed -e "26s/.*/user_tcl_shell_cmd = 'tclsh8.5'/" -i '' conf/userconf.py;
          ;;
      esac
    fi

# command to run tests
script:
  - coverage run --branch --source=opensauce --omit=opensauce/textgrid.py -m unittest test

after_success:
  - codecov

notifications:
  email:
    recipients:
      - teryu@alum.mit.edu
    on_success: always
    on_failure: always
