sudo: enabled
language: python

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: osx
      language: generic
      env: TOXENV=py27
    - os: osx
      language: generic
      env: TOXENV=py36
before_install:
  - ./.travis/before_install.sh

install:
  - ./.travis/install.sh

before_script:
  - cd $TRAVIS_BUILD_DIR
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cp conf/ciconf_linux.py conf/userconf.py; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp conf/ciconf_osx.py conf/userconf.py; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git lfs pull; fi
# command to run tests
script: coverage run --branch --source=opensauce --omit=opensauce/textgrid.py -m unittest test
after_success:
  - codecov

notifications:
  email:
    recipients:
      - teryu@alum.mit.edu
    on_success: always
    on_failure: always
